[theme]
# Core colors
primaryColor = "#000000ff"   
secondaryColor = "#fcfcfcff"             # Buttons, highlights, focus
backgroundColor = "#d1d1d1ff"            # Main page background
secondaryBackgroundColor = "#ffffffff"   # Sidebar background
textColor = "#8d1b1bff"                   # Text

# Additional theme options (Streamlit will compute hover/focus from these)
successColor = "#28A745"                # For success messages
warningColor = "#FFC107"                # For warning messages
errorColor = "#DC3545"                  # For errors
infoColor = "#17A2B8"                   # Info messages / accents
font = "geom:https://fonts.googleapis.com/css2?family=Geom&display=swap"                      # Font
